version: "3"
services:
  workoutlogapi:
    build: .
    volumes:
      - .:/app
    environment:
      NODE_ENV: test
      DB_HOST: db-test
      DB_PORT: 3306
      DB_USER: workoutuser
      DB_PASS: workout123
      DB_NAME: workout_test
      WAIT_HOSTS: db-test:3306
    command: sh -c "/wait && npm run test:functional"
    depends_on:
      - db-test
  db-test:
    image: mysql:5.7
    environment:
      MYSQL_USER: workoutuser
      MYSQL_PASSWORD: workout123
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: workout_test
